import { FC, PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

import "../styles/globals.css";
import { Lenis } from "@/components/lenis";

const inter = Inter({ subsets: ["latin"] });

const Layout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <Lenis>{children}</Lenis>
    </body>
  </html>
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default Layout;
